class RequestTypes(object):
    UNKNOWN = 'UNKNOWN'
    FIREWALL_CHANGE = 'FIREWALL CHANGE'
    DEVTOOL_INSTALL = 'DEVTOOL INSTALL'
    PERMISSION_CHANGE = 'PERMISSION CHANGE'
    DATA_EXPORT = 'DATA EXPORT'
    CLOUD_ACCESS = 'CLOUD RESOURCE ACCESS'
    NETWORK_ACCESS = 'NETWORK ACCESS'
    VENDOR_APPROVAL = 'VENDOR APPROVAL'